### ISSUE TITLE
Unknown error for non-programming person like me :)

### ISSUE THREAD

**Issue by olvier** [Herjar/radarr_sonarr_watchmon#11]
![Screenshot_20211028-192626_JuiceSSH.jpg](https://user-images.githubusercontent.com/13106409/139305961-8bfceb8a-8525-495b-9714-4dfa86af6659.jpg)

Any idea? Any information needed?
Tried to un-monitor ALL watched series in one go (36500 days).
Maybe it was too much?

**Comment by kepi** [comment]
Probably not relevant after such time but looks like your Sonarr instance died or simply couldn't handle the request and there was no exception to handle such situation.

**Comment by thx1e** [comment]
Until now the script worked fine. 
I have some kind of a similar issue with sonarr, I restarted sonarr and reinstalled several times radarr_sonarr_watchmon withtout solving the issue.
For testing what's going on, I also changed sonarr apikey and then address in config.yml to a wrong one and get the same error as with the right apikey and address.
I'm not certain the issue comes from my sonarr instance.

Here's what's displayed with the correct apikey and address in config.yml:

C:\Users\********\Desktop>"C:\Users\********\AppData\Local\Programs\Python\Python310\python.exe" "C:\Users\********\Desktop\radarr_sonarr_watchmon-master\radarr_sonarr_watchmon.py"
Enter the code "********" at https://trakt.tv/activate to authenticate your account
Authentication successful - authorization: {'access_token': '********', 'token_type': 'bearer', 'expires_in': ********, 'refresh_token': '********', 'scope': 'public', 'created_at': ********}



TV:
 Trakt: Episodes watched in last 30 days:
  ******** - S01E01: ********...
  ******** - S01E02: ...********
  ******** - S06E01: ********
  ******** - S19E01: ********
Traceback (most recent call last):
  File "C:\Users\********\Desktop\radarr_sonarr_watchmon-master\radarr_sonarr_watchmon.py", line 538, in <module>
    app.sonarr()
  File "C:\Users\********\Desktop\radarr_sonarr_watchmon-master\radarr_sonarr_watchmon.py", line 311, in sonarr
    show_episodes = self.trakt_get_episodes(self.recent_days)
  File "C:\Users\********\Desktop\radarr_sonarr_watchmon-master\radarr_sonarr_watchmon.py", line 303, in trakt_get_episodes
    print("  " + show.title + " - S"+str(season_no).zfill(2)+'E'+ str(episode_dict['number']).zfill(2) + ": " + episode_dict['title'])
TypeError: can only concatenate str (not "NoneType") to str

C:\Users\********\Desktop>pause
Press any key to continue . . .

Any idea how to solve the issue or pinpoint where it's coming from?
Thanks
